version: '3.8'
services:
  db:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
  app:
    build: .
    container_name: weather_app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/weather_db
volumes:
  dbdata:
